info:
  description: "Service for managing emp details"
  apiDocumentation: "TBD"

server:
  port: 8080

#spring:
  #data:
    #mongodb:
      #database: emp

security:
  oauth2:
    client:
      clientId: 781374084326-81kflheo8pensno4c8cuau44o21kdi85.apps.googleusercontent.com
      clientSecret: D1_heaIzRYJSCHwu4Ubahlki
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      callbackUri: http://localhost:8080/callback
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      responseType: code
      scope: openid+email
      accessType: offline
      approvalPrompt: force
      state: sessionId

